README.txt

Contributors changes

---

DefInjected/ThoughtDef/Thoughts_TraitsConditional.xml

Commit fixing a broken tag in \DefInjected\ThoughtDef\Thoughts_TraitsConditional.xml

closing tag fix in MasochistPain

---

DefInjected/SkillDef/Skills.xml
DefInjected/ThingDef/Items_Artifacts.xml

Недостающие лабели:
Для названий навыков.
Для активации у арктифактов.

0.14.1249 Fix

---

DefInjected/ChemicalDef/Chemicals.xml
DefInjected/HediffDef/Hediffs_Global_Drugs.xml
DefInjected/NeedDef/Needs.xml
DefInjected/ThingDef/Drugs.xml
DefInjected/ThoughtDef/Thoughts_Situation_Drugs.xml

Чистый ручной перевод без допинга.
Прошу прочитайте комментарии и внесите свои предложения. Завтра к утру определимся - мерджить или на доработку.
Если предложений нет и вы всем довольны, все равно напишите "ОК" для галочки.

0.15.1277 - Перевод психина.

---

DefInjected/HediffDef/Hediffs_Global_Drugs.xml
DefInjected/NeedDef/Needs.xml
DefInjected/ThingDef/Drugs.xml
DefInjected/ThoughtDef/Thoughts_Situation_Drugs.xml

Версия с вырезанными комментариями.
Поменял "устойчивость к психину" на "привыкание к психину".
Пока так. Проверьте, пишите.

a15 - Психин без комментариев

---

DefInjected/HediffDef/Hediffs_Global_Drugs.xml
DefInjected/NeedDef/Needs.xml
DefInjected/ThingDef/Drugs.xml
DefInjected/ThoughtDef/Thoughts_Situation_Drugs.xml

Версия с вырезанными комментариями.
Поменял "устойчивость к психину" на "привыкание к психину".
Пока так. Проверьте, пишите.

Alpha-15-Clean - Психин без комментариев

---

DefInjected/ChemicalDef/Chemicals.xml
DefInjected/HediffDef/Hediffs_Global_Drugs.xml
DefInjected/NeedDef/Needs.xml
DefInjected/ThingDef/Drugs.xml
DefInjected/ThoughtDef/Thoughts_Situation_Drugs.xml

Переведено и протестировано в игре.
Заменил везде привыкание на толерантность(в т.ч.  в переводе психина), т.к. иначе в игре совсем непонятно что это такое. Пусть лучше игроки погуглят. Спасибо @Ohar за идею.
Версия с комментариями, обязательно посмотрите и напишите свои мысли.

Alfa-15-Clean - Перевод люциферия и дымолиста.

---

DefInjected/HediffDef/Hediffs_Global_Drugs.xml
DefInjected/NeedDef/Needs.xml
DefInjected/ThingDef/Drugs.xml
DefInjected/ThoughtDef/Thoughts_Situation_Drugs.xml

Удалены комментарии.
Для люциферия добавлены строки:
```
<Luciferium.ingestible.ingestCommandString>
<Luciferium.ingestible.ingestReportString>
```
Добавлены уровни толерантости для Дымолиста.
Примечание: перевел small(20%), large(50%) и massive(80%) как небольшая, средняя и сильная соответственно.
Добавлен уровень аддикции люциферия.
Примечание: unmet переведено как "потребность"

Alfa-15-Clean: Хотфикс для пула #50 с учетом замечаний #51 V2.

---

DefInjected/ThingCategoryDef/ThingCategories.xml

Перевёл метки для наркотиков и растительных остатков

Translate labels for drugs and plantmatter

---

DefInjected/JobDef/Jobs_Misc.xml
DefInjected/JobDef/Jobs_Work.xml

Add translation for drilling and FermentingBarrel-related jobs.

closes #72. Add translation for drilling and FermentingBarrel-related jobs.

---

DefInjected/NeedDef/Needs_Drugs.xml

Edit Needs_Drugs.xml

---

DefInjected/ThingDef/Various_Stone.xml

[0.15.1284] fix #120. Unify stone block names

---

DefInjected/PawnKindDef/PawnKinds_Animal_Farm.xml
DefInjected/ThingDef/Races_Animal_BigCats.xml
DefInjected/ThingDef/Races_Animal_Birds.xml
DefInjected/ThingDef/Races_Animal_Farm.xml
DefInjected/ThingDef/Races_Animal_Giant.xml
DefInjected/ThingDef/Races_Animal_Insect.xml
DefInjected/ThingDef/Races_Animal_Pet.xml
DefInjected/ThingDef/Races_Animal_Rodentlike.xml
DefInjected/ThingDef/Races_Animal_Temperate.xml
DefInjected/ThingDef/Races_Animal_Tropical.xml
DefInjected/ThingDef/Races_Animal_WildCanines.xml
DefInjected/ThingDef/Races_Mechanoid.xml

Причёсан текст мобов
В русском языке [приставка _мега-_ пишется без дефиса](http://new.gramota.ru/spravka/buro/search-answer?s=280043), поэтому сделал их _мегапауком_ и _мегаскарабеем_.
В настоящий момент _Spelopede_ переведено как _пещерный жук_. Предлагаю заменить на _пещерник_, так как _spelo_ (греч.) — пещера, а окончание _ped_ в английском примерно обозначает _ноги_, т. е. буквальный перевод — _пещероход_, _пещеролаз_, _пещероног_.

[0.15.1284] fix #135. Update Defs\ThingsDef_Races

---

DefInjected/PawnRelationDef/PawnRelations_Misc.xml
DefInjected/TaleDef/Tales_DoublePawn_Relationships.xml
DefInjected/ThoughtDef/Thoughts_Memory_Social.xml
DefInjected/ThoughtDef/Thoughts_Situation_Social.xml
Keyed/Messages.xml

Fix "bond" translation so it match the context - in PawnRelations_Misc.xml and Tales_DoublePawn_Relationships.xml

Close #140 Animal Bond

---

DefInjected/FactionDef/Factions_Hidden.xml

Fix translation errors about spacers faction in Factions_Hidden.xml

[0.15.1284]close #144 Spacers

---

DefInjected/JobDef/Jobs_Misc.xml

Enhcance translation of "ingest" in Jobs_Misc.xml

[0.15.1284]close #145

---

DefInjected/PawnKindDef/PawnKinds_Animal_Tropical.xml
DefInjected/ThingDef/Races_Animal_Tropical.xml

Переименовал бумалопу в соотвтествии с заданием #143.

Close #143. Rename boomalope

---

DefInjected/ThingCategoryDef/ThingCategories.xml

Порядок следования объектов соответствует оригиналу.
Добавлены комментарии-разделители.
Удален тэг **`<Resources.label>`**.
Добавлен тэг **`<CorpsesInsect.label>`**.
Небольшие правки по тексту.

[0.15.1284] Fix #179. Update ThingCategories.xml.

---

Keyed/Dates.xml
Keyed/Designators.xml
Keyed/Dialog_Trees.xml

Make translation more close to the original and fix translation errors

[0.15.1248]close #169 Translation fix

---

DefInjected/ResearchProjectDef/ResearchProjects_Tier1_Misc.xml
DefInjected/ResearchProjectDef/ResearchProjects_Tier2_Misc.xml
DefInjected/ResearchProjectDef/ResearchProjects_Tier3_Misc.xml
DefInjected/ResearchProjectDef/ResearchProjects_Tier4_Misc.xml
DefInjected/ResearchProjectDef/ResearchProjects_Tier4_Ship.xml

Актуальное задание.
1) **ResearchProjectDefs\ResearchProjects_Tier1_Misc.xml**
* Переименовать "**Pemmican**" в "**пеммикан**".
* Опционально: Исправить перевод объекта **DrugProduction**.
2) **ResearchProjectDefs\ResearchProjects_Tier2_Misc.xml**
* Согласовать перевод для объекта **PsychiteRefining**.
* Убрать перевод для объекта **GoJuiceProduction**.
* Удалить дефис из слова "**крипто-сна**" в тэге **`<MicroelectronicsBasics.description>`**.
* В перевод объекта **GunTurrets** буква "**Е**" использована вместо буквы "**Ё**" в слове "**пулеметные**".
3) **ResearchProjectDefs\ResearchProjects_Tier3_Misc.xml**
* Согласовать перевод для объекта **MoisturePump** с файлом **ThingDef\Buildings_Misc.xml**
4) **ResearchProjectDefs\ResearchProjects_Tier4_Misc.xml**
* Убрать дефис из перевода …

[0..15.1284] fix #162. Edit ResearchProjectDef.

---

Keyed/PlayInterface.xml
Keyed/ScenParts.xml
Keyed/Skills.xml
Keyed/WorkTags.xml

Translation fix in:
- PlayInterface.xml
- ScenParts.xml
- Skills.xml
- WorkTags.xml

[0.12.1284]close #175 Translation fix

---

DefInjected/ThoughtDef/Thoughts_Memory_Social.xml

"Любимого человека" тоже исправил, для единообразия и по аналогии с немецким переводом.

Fix #207. Fix long string for bond.

---

Keyed/Misc_Gameplay.xml

Fix #210. '(связь)' to '(привяз-ть)'

---

Keyed/Misc_Gameplay.xml

Fix #215, "недостаточно энергии"

---

DefInjected/ThoughtDef/Thoughts_Situation_General.xml

Fix #216. Fix 'подтянуть пояс'

---

DefInjected/RecipeDef/Recipes_Add.xml

Fix #213. Fix skulpture small

---

DefInjected/ThingDef/Races_Animal_Arid.xml
DefInjected/ThingDef/Races_Animal_Bears.xml
DefInjected/ThingDef/Races_Animal_BigCats.xml
DefInjected/ThingDef/Races_Animal_Birds.xml
DefInjected/ThingDef/Races_Animal_Farm.xml
DefInjected/ThingDef/Races_Animal_Giant.xml
DefInjected/ThingDef/Races_Animal_Hares.xml
DefInjected/ThingDef/Races_Animal_Insect.xml
DefInjected/ThingDef/Races_Animal_Pet.xml
DefInjected/ThingDef/Races_Animal_Rodentlike.xml
DefInjected/ThingDef/Races_Animal_Temperate.xml
DefInjected/ThingDef/Races_Animal_WildCanines.xml
DefInjected/ThingDef/Races_Humanlike.xml
DefInjected/ThingDef/Races_Mechanoid.xml

Close #142. Remove trash comments

---

DefInjected/ThoughtDef/Thoughts_Memory_Social.xml

Fix #203. Fix InsultedMood label and description

---

DefInjected/ResearchProjectDef/ResearchProjects_Tier4_Ship.xml

Fix #231, duplicated cryptosleep researches

---

DefInjected/InstructionDef/Instructions.xml

Close #228. Use "верстак учёного"

---

DefInjected/ThingDef/Buildings_Production.xml

Close #183. "Стол для резки камня" нормально выглядит и помещается на UI

Close #183, Fix TableStonecutter

---

Keyed/Skills.xml

Fix #214. Fix style

---

DefInjected/WorkGiverDef/WorkGivers.xml

Fix #250, hunt gerund

---

DefInjected/HediffDef/Hediffs_Local_Injuries.xml

Fix #259, crack label

---

Keyed/Letters.xml

Fix #225, addiction strings

---

DefInjected/ThingDef/Items_Resource_Manufactured.xml

Fix #209, HerbalMedicine description

---

DefInjected/RecipeDef/Recipes_Add.xml
DefInjected/ThingDef/Items_Drugs.xml
DefInjected/ThingDef/Items_Resource_RawPlant.xml
DefInjected/ThingDef/Plants_Cultivated_Farm.xml

Fix #246. Предлагаю дискуссию вести более предметно, в рамках пулреквеста.

Fix #246. Rename smokeleaf joint

---

Keyed/Designators.xml

Fix translation in <TerrainIsAlready>, at Designators.xml
В игре проверено, всё влезает, проблем с падежами не возникает. Вроде =)

Close #269

---

Keyed/Alerts.xml

Fix incorrect stylistics in <NeedWarmClothesDesc2>

Close #247 - Translation fix. (Швейная машинка)

---

DefInjected/ThoughtDef/Thoughts_Exotic.xml
DefInjected/ThoughtDef/Thoughts_Memory_Death.xml
DefInjected/ThoughtDef/Thoughts_Memory_Eating.xml
DefInjected/ThoughtDef/Thoughts_Memory_Misc.xml
DefInjected/ThoughtDef/Thoughts_Random.xml
DefInjected/ThoughtDef/Thoughts_Situation_Drugs.xml
DefInjected/ThoughtDef/Thoughts_Situation_General.xml
DefInjected/ThoughtDef/Thoughts_Situation_Needs.xml
DefInjected/ThoughtDef/Thoughts_Situation_RoomStats.xml
DefInjected/ThoughtDef/Thoughts_Situation_Special.xml
DefInjected/ThoughtDef/Thoughts_Situation_Traits.xml
DefInjected/ThoughtDef/Thoughts_Situation_TraitsPerm.xml

Fix #273. Исправил опечатки. Добавил "ё", где надо. Кое-где сделал перевод более человечным.

Refactor thoughts

---

DefInjected/ThoughtDef/Thoughts_Exotic.xml
DefInjected/ThoughtDef/Thoughts_Memory_Misc.xml
DefInjected/ThoughtDef/Thoughts_Memory_Social.xml
DefInjected/ThoughtDef/Thoughts_Situation_Drugs.xml
DefInjected/ThoughtDef/Thoughts_Situation_General.xml
DefInjected/ThoughtDef/Thoughts_Situation_Needs.xml
DefInjected/ThoughtDef/Thoughts_Situation_RoomStats.xml
DefInjected/ThoughtDef/Thoughts_Situation_Traits.xml

Fix #264. Исправил только то, что касалось суффиксов и окончаний для родовой универсальности. Для других ошибок будет отдельная задача.

Fix #264 verb gender suffices for thoughts

---

DefInjected/WorkGiverDef/WorkGivers.xml

Attempt to fix incorrect phrase about switch and it's priority at DefInjected/WorkGiverDef/WorkGivers.xml
Есть сильное подозрение, что сие работать будет криво, даже если я выбрала верные строчки. Протестируйте, пожалуйста. В последнее время не играю вообще.

close #267 - Translation fix

---

DefInjected/ThoughtDef/Thoughts_Situation_Social.xml

Fix incorrect phrase about "opinion of lover", at DefInjected/ThoughtDef/Thoughts_Situation_Social.xml

Close #268 - Translation fix

---

DefInjected/WorkTypeDef/WorkTypes.xml
Keyed/FloatMenu.xml

Место действия: DefInjected/WorkTypeDef/WorkTypes.xml  и  Keyed/FloatMenu.xml 
Причина: #251 и #253

#251 and  #253  gerunds fix 

---

DefInjected/ThoughtDef/Thoughts_Situation_RoomStats.xml

Fix #261. Refactor room stat thoughts

---

DefInjected/IncidentDef/Incidents_Various_Bad.xml

Fix incorrect translation of <ToxicFallout.letterText> in DefInjected/IncidentDef/Incidents_Various_Bad.xml

Close #297 - <ToxicFallout.letterText>

---

DefInjected/WorkGiverDef/WorkGivers.xml
DefInjected/WorkTypeDef/WorkTypes.xml
Keyed/FloatMenu.xml

Work types givers

---

DefInjected/TraitDef/Traits_Spectrum.xml
DefInjected/WorkGiverDef/WorkGivers.xml
DefInjected/WorkTypeDef/WorkTypes.xml
DefInjected/WorldObjectDef/WorldObjects.xml

Моя первая попытка переводить самой, а не за другими. Пожелайте мне удачи =)

#321 Time assignment -> work type def

---

Keyed/MainTabs.xml
Keyed/Menu_Options.xml
Keyed/Menus_Main.xml

Close #332, MainTabs-MenusMain

---

Keyed/ITabs.xml
Keyed/Incidents.xml
Keyed/Letters.xml

Close #331. Translate Keyed: ITabs-Letters

---

Keyed/Messages.xml

Close #333. Update Keyed: Messages

---

DefInjected/ThingDef/Buildings_Joy.xml
DefInjected/ThingDef/_ThingDef_BlueprintsAndFrames.xml

Fix translation of horseshoes pin's description in: Buildings_Joy.xml and _ThingDef_BlueprintsAndFrames.xml
Почему колышек, а не штырь? А потому что описание "старинной игры": "подковами и вбитым в землю колышком".
Сразу рисуется Древняя Русь... С суровым челябинским штырём для подковы.

close #343 - Horseshoes pin translation (new)

---

Keyed/Misc.xml
Keyed/Misc_Gameplay.xml

Close #334. Update Keyed: Misc -> MiscGameplay

---

DefInjected/ThoughtDef/Thoughts_Memory_RoomStats.xml
DefInjected/ThoughtDef/Thoughts_Situation_RoomStats.xml

Close #320. Room Stats.

---

DefInjected/ThoughtDef/Thoughts_Memory_Death.xml
DefInjected/ThoughtDef/Thoughts_Memory_Debug.xml
DefInjected/ThoughtDef/Thoughts_Memory_Eating.xml
DefInjected/ThoughtDef/Thoughts_Memory_Gatherings.xml
DefInjected/ThoughtDef/Thoughts_Memory_Misc.xml

Close #317. Thoughts_Exotic-Thoughts_Memory_Misc

---

Keyed/Skills.xml
Keyed/WITabs.xml

Close #335. Update Keyed: Skills -> WITabs

---

DefInjected/PawnKindDef/PawnKinds_Animal_Giant.xml
DefInjected/ThingDef/Buildings_Security.xml
DefInjected/ThingDef/Items_Drugs.xml
DefInjected/ThingDef/Items_Exotic.xml
DefInjected/ThingDef/Items_Resource_Manufactured.xml
DefInjected/ThingDef/Items_Resource_Stuff.xml
DefInjected/ThingDef/Races_Animal_Giant.xml
DefInjected/ThingDef/Things_Special.xml
DefInjected/ThingDef/Weapons_Artillery.xml

Изменений много разных. Просьба проверить, точно ли я всё верно удалила. 
RectTrigger.description в оригинале найти не смогла.

#316 thing def upd

---

DefInjected/ThoughtDef/Thoughts_Memory_Social.xml
DefInjected/ThoughtDef/Thoughts_Random.xml
DefInjected/ThoughtDef/Thoughts_Situation_Drugs.xml
DefInjected/ThoughtDef/Thoughts_Situation_General.xml

Close #318. Thoughts_Memory_Social-Thoughts_Situation_General

---

DefInjected/MentalStateDef/MentalStates_Mood.xml
DefInjected/MentalStateDef/MentalStates_Special.xml

Close #309. Update MentalStateDef

---

Backstories/Backstories.xml

В основном - приведение к нормальному формату переносов строк. А также минимальные исправления "помещаемости" текста.
Можно мёрджить как есть, чтобы быстрее был материал для работы, тем более, что им интересуются.

Backstories small fixes & nice newlines

---

DefInjected/TerrainDef/Terrain_Floors.xml
DefInjected/ThingDef/_ThingDef_BlueprintsAndFrames.xml

Металлоплитка не влезает на строчку. Изначально она и была "металлической плиткой".
Проставлены "ё", где заметил.
Исправлена "асфальтовая" плитка. Изначальный вариант, но ошибочный.

Floor Tiles Fixes

---

DefInjected/InstructionDef/Instructions.xml
DefInjected/JobDef/Jobs_Misc.xml
Keyed/FloatMenu.xml
Keyed/Messages.xml
Keyed/Misc_Gameplay.xml

Fix #434, fix #435. Fix "Equip" translations

---

Backstories/Backstories.xml

Исправил и раскомментил перевод бэкстори от @DanPrisoner

Fix DanPrisoner's translation

---

Keyed/Designators.xml
Keyed/Dialogs_Various.xml
Keyed/FloatMenu.xml

Close #472. Keyed - part 1

---

Keyed/Dialogs_Various.xml
Keyed/ITabs.xml
Keyed/Incidents.xml
Keyed/Letters.xml

Close #473. Keyed - part 2

---

Keyed/Menu_Options.xml
Keyed/Menus_Main.xml
Keyed/Messages.xml

Close #474. Translate Keyed - part 3

---

Keyed/Dates.xml
Keyed/Letters.xml
Keyed/Misc_Gameplay.xml
Keyed/Time.xml

475 keyed 4

---

Keyed/Dialog_StatsReports.xml
Keyed/Dialogs_Various.xml
Keyed/FloatMenu.xml
Keyed/GameplayCommands.xml
Keyed/Letters.xml
Keyed/MainTabs.xml
Keyed/Misc.xml
Keyed/Misc_Gameplay.xml
Keyed/WorkTags.xml

Close #486. Translate Keyed - part 5

---

DefInjected/ThingDef/Apparel_Belts.xml
DefInjected/ThingDef/Apparel_Hats.xml
DefInjected/ThingDef/Apparel_Shield.xml
DefInjected/ThingDef/Buildings_Ancient.xml
DefInjected/ThingDef/Buildings_Misc.xml
DefInjected/ThingDef/Filth_Various.xml
DefInjected/ThingDef/Gas_Various.xml
DefInjected/ThingDef/Items_Drugs.xml
DefInjected/ThingDef/Items_Unfinished.xml
DefInjected/ThingDef/Plants_Special.xml
DefInjected/ThingDef/Plants_Wild_Temperate.xml
DefInjected/ThingDef/Things_Mote.xml
DefInjected/ThingDef/Things_Special.xml
DefInjected/ThingDef/Weapons_Guns.xml
DefInjected/ThingDef/_ThingDef_BlueprintsAndFrames.xml

466 thing def

---

DefInjected/TerrainDef/Terrain_FloorsStoneTile.xml
DefInjected/TerrainDef/Terrain_Floors_Burned.xml
DefInjected/TerrainDef/Terrain_Road.xml
DefInjected/TerrainDef/Terrain_Water.xml

467 terrain def

---

DefInjected/TraitDef/Traits_Spectrum.xml

Fix 285, fix 298. Correct translation for pawns' beauty

---

DefInjected/TraitDef/Traits_Singular.xml

Fix #509, NightOwl description

---

Keyed/Misc_Gameplay.xml

Translate <CaravanBaseMovementTime> and <CurrentTileMovementTime> to be more understandable.

close #525 - MovementTime transl. fix

---

DefInjected/TraitDef/Traits_Singular.xml

Translate Wimp

---

Backstories/Backstories.xml

В ближайшие 2-3 дня полноценно с этим я работать не смогу: наслаждайтесь.
К разбору полётов приглашаются все желающие: @EcherArt, @Elevator89, @Dimonasdf, @Orontion -- и остальные, если кого забыл.

WarRefugee81_UnstableButcher98: close #443 and some in #442

---

DefInjected/InteractionDef/Interactions_Animal.xml
DefInjected/InteractionDef/Interactions_Directed.xml
DefInjected/InteractionDef/Interactions_Romance.xml
DefInjected/InteractionDef/Interactions_Social.xml

Надо выбрать один из реквестов: этот или #529

Neutral interactions

---

Keyed/Credits.xml
Keyed/Designators.xml
Keyed/Dialog_StatsReports.xml
Keyed/Dialogs_Various.xml
Keyed/FloatMenu.xml
Keyed/GameplayCommands.xml

Close #590. Translate some keyed files

---

DefInjected/SiteCoreDef/SiteCoreDefs.xml
Keyed/ITabs.xml
Keyed/Incidents.xml
Keyed/Letters.xml

590 keyed2

---

Keyed/MainTabs.xml
Keyed/Menu_Options.xml
Keyed/Menus_Main.xml
Keyed/Messages.xml
Keyed/Misc.xml
Keyed/Misc_Gameplay.xml
Keyed/ScenParts.xml
Keyed/Time.xml
Keyed/WITabs.xml

Close #591. Translate Keyed-3

---

DefInjected/InstructionDef/Instructions.xml
DefInjected/InteractionDef/Interactions_Directed.xml
DefInjected/ItemCollectionGeneratorDef/ItemCollectionGenerators_General.xml
DefInjected/ItemCollectionGeneratorDef/ItemCollectionGenerators_Specific.xml
DefInjected/JobDef/Jobs_Joy.xml
DefInjected/JobDef/Jobs_Misc.xml
DefInjected/KeyBindingCategoryDef/KeyBindingCategories.xml
DefInjected/KeyBindingDef/KeyBindings.xml
DefInjected/MentalBreakDef/MentalBreaks_Mood.xml

Close #567, InstructionDef-MentalBreakDef

---

DefInjected/MentalStateDef/MentalStates_Mood.xml

Close #568, MentalStateDef

---

DefInjected/SiteCoreDef/SiteCoreDefs.xml
DefInjected/SitePartDef/SitePartDefs.xml
DefInjected/SpecialThingFilterDef/SpecialThingFilters.xml
DefInjected/StatCategoryDef/StatCategories.xml
DefInjected/StatDef/Stats_Apparel.xml
DefInjected/StatDef/Stats_Basics_General.xml
DefInjected/StatDef/Stats_Building_Special.xml
DefInjected/StatDef/Stats_Pawns_General.xml
DefInjected/StatDef/Stats_Pawns_Social.xml
DefInjected/StatDef/Stats_Pawns_WorkMedical.xml
DefInjected/StatDef/Stats_Pawns_WorkRecipes.xml
DefInjected/StatDef/Stats_Weapons_Melee.xml
DefInjected/ThingCategoryDef/ThingCategories.xml

Close #581, SiteCoreDef-ThingCategoryDef

---

DefInjected/ThoughtDef/Thoughts_Exotic.xml
DefInjected/ThoughtDef/Thoughts_Memory_Misc.xml
DefInjected/ThoughtDef/Thoughts_Memory_Social.xml
DefInjected/ThoughtDef/Thoughts_Situation_Drugs.xml
DefInjected/ToolCapacityDef/ToolCapacity.xml
DefInjected/TrainableIntelligenceDef/TrainableIntelligence.xml
DefInjected/TraitDef/Traits_Singular.xml
DefInjected/WorkGiverDef/WorkGivers.xml
DefInjected/WorkTypeDef/WorkTypes.xml
DefInjected/WorldObjectDef/WorldObjects.xml
Keyed/Enums.xml

Close #588, ThoughtDef-WorldObjectDef

---

DefInjected/RecipeDef/Recipes_Surgery.xml
DefInjected/ThingDef/Ethereal_OrbitalStrikes.xml
DefInjected/ThingDef/Ethereal_SignalActions.xml
DefInjected/ThingDef/Ethereal_Various.xml
DefInjected/ThingDef/Items_Drugs.xml
DefInjected/ThingDef/Items_Exotic.xml
DefInjected/ThingDef/Items_Resource_Manufactured.xml
DefInjected/ThingDef/Items_Resource_RawPlant.xml
DefInjected/ThingDef/Items_Resource_Shell.xml

Close #583, ThingDef, part 2

---

DefInjected/ThingDef/Skyfallers_Various.xml
DefInjected/ThingDef/Things_Mote.xml
DefInjected/ThingDef/Things_Special.xml
DefInjected/ThingDef/Various_Stone.xml
DefInjected/ThingDef/Weapons_Guns.xml
DefInjected/ThingDef/Weapons_Melee.xml
DefInjected/ThingDef/Weapons_RangedNeolithic.xml

Close #586, ThingDef, part 5

---

DefInjected/RulePackDef/RulePacks_Damage.xml
DefInjected/RulePackDef/RulePacks_DamageEvent.xml
DefInjected/RulePackDef/RulePacks_Maneuvers.xml
DefInjected/RulePackDef/RulePacks_NameMakers_Factions.xml
DefInjected/RulePackDef/RulePacks_NameMakers_WorldFeatures.xml
DefInjected/RulePackDef/RulePacks_Transitions.xml

_RulePacks_Art_DescriptionRoot - checked_
_RulePacks_Art_ImagesTaleless - checked_
_RulePacks_Art_NameRoots - checked_
_RulePacks_Art_PhysicalDescriptionRoots - checked_
RulePacks_Combat - SKIPPED (Вижу, что уже в работе)
RulePacks_Damage - TODO (Скопирован из -de, отформатированный английский)
RulePacks_DamageEvent - TODO (Скопирован из -de, отформатированный английский)
_RulePacks_Global - checked_
_RulePacks_InteractionsExtra - checked_
RulePacks_Maneuvers - TODO (Скопирован из -de, отформатированный немецкий)
_RulePacks_NameMaker_World - checked_
_RulePacks_NameMakers_Animals - checked_
RulePacks_NameMakers_Factions - done (Небольшие обновления)
_RulePacks_NameMakers_People - checked_
_RulePacks_NameMakers_Scenarios - checked_
_RulePacks_NameMakers_Traders - checked_ …

some work on rulepacks 18

---

DefInjected/DamageDef/Damages_MeleeWeapon.xml
DefInjected/RulePackDef/RulePacks_Maneuvers.xml
DefInjected/ToolCapacityDef/ToolCapacity.xml

Кровь, кишки и расчленёнка, часть 2

---

DefInjected/RulePackDef/RulePacks_DamageEvent.xml

Close #625, Translate DamageEvents

---

DefInjected/TaleDef/Tales_Caravan.xml

Translate Translate_Tales_Caravan.xml from <CaravanFormed.label> to <CaravanFled.label> and their respective descriptions.

#626-Translate_Tales_Caravan.xml

---

DefInjected/TaleDef/Tales_Caravan.xml

Close #631. Translate CaravanRemoteMining

---

DefInjected/TaleDef/Tales_DoublePawn.xml
DefInjected/TaleDef/Tales_Event.xml
DefInjected/TaleDef/Tales_SinglePawn.xml

Close #632. Tales: KilledBy, LaunchedShip, SocialFight

---

DefInjected/TaleDef/Tales_DoublePawn.xml
DefInjected/TaleDef/Tales_Event.xml
DefInjected/TaleDef/Tales_Health.xml

633 collapse dodged wounded

---

DefInjected/TaleDef/Tales_Health.xml

Close #634. Translate tales: Downed, KilledLongRange

---

DefInjected/TaleDef/Tales_Health.xml

Close #635, Translate KilledMelee tale

---

DefInjected/PawnKindDef/PawnKinds_Animal_Arid.xml
DefInjected/PawnKindDef/PawnKinds_Animal_Bears.xml
DefInjected/PawnKindDef/PawnKinds_Animal_BigCats.xml
DefInjected/PawnKindDef/PawnKinds_Animal_Birds.xml
DefInjected/PawnKindDef/PawnKinds_Animal_Farm.xml
DefInjected/PawnKindDef/PawnKinds_Animal_Giant.xml
DefInjected/PawnKindDef/PawnKinds_Animal_Hares.xml
DefInjected/PawnKindDef/PawnKinds_Animal_Insect.xml
DefInjected/PawnKindDef/PawnKinds_Animal_Pet.xml
DefInjected/PawnKindDef/PawnKinds_Animal_Rodentlike.xml
DefInjected/PawnKindDef/PawnKinds_Animal_Temperate.xml
DefInjected/PawnKindDef/PawnKinds_Animal_Tropical.xml
DefInjected/PawnKindDef/PawnKinds_Animal_WildCanines.xml
DefInjected/PawnKindDef/PawnKinds_Mechanoid.xml
DefInjected/PawnKindDef/PawnKinds_Mercenary.xml
DefInjected/PawnKindDef/PawnKinds_Outlander.xml
DefInjected/PawnKindDef/PawnKinds_Pirate.xml
DefInjected/PawnKindDef/PawnKinds_Player.xml
DefInjected/PawnKindDef/PawnKinds_Spacer.xml
DefInjected/PawnKindDef/PawnKinds_Special.xml

Убрано лишнее, добавлено нужное. Все заголовки переведены в нижний регистр.

#249 Заяц женского пола

---

DefInjected/PawnCapacityDef/PawnCapacity.xml
DefInjected/TaleDef/Tales_Health.xml

636 tales killed major threat killed capacity

---

DefInjected/ThingDef/Items_Resource_Manufactured.xml

Items_Resource_Manufactured.xml misprint fix

---

DefInjected/TaleDef/Tales_Caravan.xml
DefInjected/TaleDef/Tales_Health.xml

639 gave birth caravan ambushed by humanlike caravan ambushed by manhunter

---

DefInjected/TaleDef/Tales_Incident.xml

642 tales aurora flashstorm tornado

---

DefInjected/RulePackDef/RulePacks_Global.xml
DefInjected/TaleDef/Tales_Incident.xml

644 tales manhunter pack ship part crash

---

DefInjected/TaleDef/Tales_Caravan.xml
DefInjected/TaleDef/Tales_Incident.xml
DefInjected/TaleDef/Tales_Job.xml

Translate Tales: Eclipse, JourneyOffer, MinedValuable

---

DefInjected/RulePackDef/RulePacks_Transitions.xml
DefInjected/TaleDef/Tales_Job.xml

646 tales completed long construction project completed long crafting project attended party

---

DefInjected/TaleDef/Tales_Job.xml

647 tales meditated visited grave

---

DefInjected/TaleDef/Tales_Job.xml

Translate PlayedGame..EnteredCryptosleep tales

---

DefInjected/TaleDef/Tales_Job.xml
DefInjected/TaleDef/Tales_SinglePawn.xml

Close #649, Translate Stripped tale, fix WalkedNaked

---

Backstories/Backstories.xml

Backstories: SpaceCadet12..MutinousCaptain49

---

DefInjected/TaleDef/Tales_DoublePawn.xml
DefInjected/TaleDef/Tales_Job.xml

Close #650. Tales: GainedMasterSkillWithPassion, IncreasedMenagerie

---

Backstories/Backstories.xml

Close #790. Backstories: ApprenticeOracle81..ArtifactHunter88

---

Backstories/Backstories.xml

Close #791. Backstories: ChildResearcher33..DeepSpaceSurveor17

---

Backstories/Backstories.xml

#825. Translate backstories: Freethinker38..MercenaryLord58

---

Keyed/Dialogs_Various.xml
Keyed/MainTabs.xml

Add translation "Food restriction"

Some translate

---

Backstories/Backstories.xml

Close #816. Add female tags to backstories

---

DefInjected/HediffDef/Hediffs_Local_Injuries.xml
DefInjected/HediffDef/Hediffs_Local_Misc.xml
DefInjected/IncidentDef/Incidents_Caravan_All.xml
DefInjected/IncidentDef/Incidents_Map_Threats.xml
DefInjected/IncidentDef/Incidents_World_Quests.xml
DefInjected/InstructionDef/Instructions.xml
DefInjected/JobDef/Jobs_Work.xml
DefInjected/WorkGiverDef/WorkGivers.xml
Keyed/Designators.xml

Выглядит чудовищно, т.к. атом убирает ненужные пробелы

Implement some fixes after the readout

---

Keyed/Menu_KeyBindings.xml
Keyed/Menus_Main.xml
Keyed/Messages.xml
Keyed/Misc_Gameplay.xml

Возвращение пробелов-3. Слэшер.

More fixes from readout

---

Keyed/Dialogs_Various.xml
Keyed/FloatMenu.xml
Keyed/ITabs.xml
Keyed/Letters.xml

Even more fixes from readout

---

DefInjected/HairDef/HairsGeneral.xml
DefInjected/ThingDef/Buildings_Furniture.xml
DefInjected/ThingDef/ImpliedDefs.xml
DefInjected/ThingDef/RangedIndustrial.xml

haircuts, sleeping spots, 2 other

fix after readout

---

DefInjected/ThoughtDef/Thoughts_Situation_Needs.xml

Если вариант с титлами не ок - просто пушьте первые два коммита. Сорри за Атом и его пробелы.

#897 recreational titles and desc

---

Keyed/Enums.xml
Keyed/FloatMenu.xml
Keyed/GameplayCommands.xml
Keyed/Grammar.xml
Keyed/ITabs.xml
Keyed/Incidents.xml

Translate Keyed, part 2

---

DefInjected/BodyDef/Bodies_Mechanoid.xml
DefInjected/BodyPartDef/BodyParts_Mechanoid.xml
DefInjected/BodyPartGroupDef/BodyPartGroups.xml
DefInjected/ConceptDef/Concepts_NotedOpportunistic.xml
DefInjected/ConceptDef/Concepts_TriggeredModal.xml
DefInjected/DamageDef/Damages_MeleeWeapon.xml
DefInjected/DifficultyDef/Difficulties.xml
DefInjected/DutyDef/Duties_Gatherings.xml
DefInjected/ExpansionDef/ExpansionDefs.xml
DefInjected/ExpectationDef/Expectations.xml
DefInjected/FactionDef/Factions_Hidden.xml
DefInjected/FactionDef/Factions_Misc.xml
DefInjected/GameConditionDef/Buildings_Exotic.xml
DefInjected/GameConditionDef/GameConditions_Misc.xml
DefInjected/GatheringDef/Gatherings.xml
DefInjected/HairDef/HairsGeneral.xml

close #934 - update translation
Updated and improved translation in Definjected, from BodyDef to HairDef.

BodyDef-HairDef upd

---

DefInjected/SpecialThingFilterDef/SpecialThingFilters.xml

Fix typo in AllowSmeltableApparel.label
This is horrible.

Fix typo AllowSmeltableApparel

---

DefInjected/GameConditionDef/GameConditions_Misc.xml

Переместил английские и русские тексты из IncidentDef в GameConditions_Misc. Нужно сравнить и или скомпоновать лучший вариант. 
Английские тексты перенесены, что было понятно, что перевод каких строк ранее находился в IncidentDef. Перед мержем я их верну как было.

Move texts from IncidentDef to GameConditions_Misc.xml

---

DefInjected/ThoughtDef/Thoughts_Memory_Lost.xml

947 def injected thought def thoughts memory lost

---

Keyed/Letters.xml
Keyed/MainTabs.xml

931 keyed 3

---

DefInjected/ThingDef/Races_Animal_Farm.xml
DefInjected/ThingDef/Races_Animal_Tropical.xml
DefInjected/ThingDef/Races_Animal_WildCanines.xml
DefInjected/ThingDef/Races_Mechanoid.xml
DefInjected/ThingDef/RangedIndustrial.xml
DefInjected/ThingDef/RangedIndustrialConsumable.xml
DefInjected/ThingDef/RangedMechanoid.xml

#945 Translate ThingDef: Races_Animal_Farm-RangedMechanoid

---

DefInjected/ThingCategoryDef/ThingCategories.xml
DefInjected/ThingDef/Apparel_Headgear.xml
DefInjected/ThingDef/Apparel_Various.xml
DefInjected/ThingDef/Buildings_Ancient.xml
DefInjected/ThingDef/Buildings_Furniture.xml
DefInjected/ThingDef/Buildings_Joy.xml
DefInjected/ThingDef/Buildings_Misc.xml
DefInjected/ThingDef/Buildings_Natural.xml
DefInjected/ThingDef/Buildings_Production.xml
DefInjected/ThingDef/Buildings_Security.xml
DefInjected/ThingDef/Buildings_Security_Turrets.xml
DefInjected/ThingDef/Buildings_Ship.xml
DefInjected/ThingDef/Buildings_Special.xml
DefInjected/ThingDef/Buildings_Structure.xml
DefInjected/ThingDef/Effecter_Damage.xml
DefInjected/ThingDef/Filth_Various.xml

Close #943 Translate ThingCategoryDef-ThingDef/Filth_Various

---

Core/DefInjected/ConceptDef/Concepts_NotedSelfshow.xml

Описание раздела "Одежда" в обучении не совпадало с названиями кнопок.

Fix outfits description in tutorial

---

Core/DefInjected/BodyDef/Bodies_Mechanoid.xml
Core/DefInjected/InspirationDef/Inspirations.xml
Core/DefInjected/InstructionDef/Instructions.xml
Core/DefInjected/JobDef/Jobs_Gatherings.xml
Core/DefInjected/JobDef/Jobs_Misc.xml
Core/DefInjected/KeyBindingDef/ImpliedDefs.xml
Core/DefInjected/MainButtonDef/MainButtons.xml
Core/DefInjected/MentalStateDef/MentalStates_Mood.xml
Core/DefInjected/NeedDef/Needs.xml
Core/DefInjected/PawnColumnDef/PawnColumns_Misc.xml
Core/DefInjected/PawnKindDef/PawnKinds_Mercenary.xml
Core/DefInjected/PawnKindDef/PawnKinds_Spacer.xml
Core/DefInjected/PawnKindDef/Races_Animal_Farm.xml
Core/DefInjected/PawnKindDef/Races_Animal_Temperate.xml
Core/DefInjected/PawnKindDef/Races_Mechanoid.xml
Core/DefInjected/PawnsArrivalModeDef/PawnsArrivalModes.xml
Core/DefInjected/ThingDef/Races_Mechanoid.xml
Royalty/DefInjected/ThingDef/Hediffs_BodyParts_Bionic_Empire.xml

937 inspitaion def pawns arrival mode def

---

Royalty/DefInjected/RecipeDef/Hediffs_BodyParts_Archotech.xml
Royalty/DefInjected/RecipeDef/Hediffs_BodyParts_Archotech_EmpireRoyal.xml
Royalty/DefInjected/RecipeDef/Hediffs_BodyParts_Bionic_Empire.xml
Royalty/DefInjected/RecipeDef/Hediffs_BodyParts_Prosthetic_Empire.xml
Royalty/DefInjected/ResearchProjectDef/Apparel_Various.xml
Royalty/DefInjected/ResearchProjectDef/ResearchProjects_Apparel.xml
Royalty/DefInjected/ResearchProjectDef/ResearchProjects_Implants.xml
Royalty/DefInjected/ResearchProjectDef/ResearchProjects_MusicalInstruments.xml

переведены все файлы в папках: RecipeDef и ResearchProjectDef

Translated Royalty recipe def research project def

---

Core/DefInjected/ThoughtDef/Alcohol_Beer.xml
Core/DefInjected/ThoughtDef/Expectations.xml
Core/DefInjected/ThoughtDef/Thoughts_Anesthetic.xml
Core/DefInjected/ThoughtDef/Thoughts_Memory_Gatherings.xml

946 thought def alcohol beer thoughts memory gatherings

---

Core/DefInjected/ThoughtDef/Thoughts_Memory_Misc.xml
Core/DefInjected/ThoughtDef/Thoughts_Memory_Social.xml
Core/DefInjected/ThoughtDef/Thoughts_Situation_General.xml
Core/DefInjected/ThoughtDef/Thoughts_Situation_Needs.xml

948 thought def thoughts memory misc thoughts situation needs

---

Core/DefInjected/ThoughtDef/GoJuice.xml
Core/DefInjected/ThoughtDef/Psychite_Flake.xml
Core/DefInjected/ThoughtDef/Psychite_Tea.xml
Core/DefInjected/ThoughtDef/Psychite_Yayo.xml
Core/DefInjected/ThoughtDef/Smokeleaf.xml
Core/DefInjected/ThoughtDef/Thoughts_Memory_Death.xml
Core/DefInjected/ThoughtDef/Thoughts_Memory_Lost.xml
Core/DefInjected/ThoughtDef/Thoughts_Memory_Misc.xml
Core/DefInjected/ThoughtDef/Thoughts_Memory_Social.xml
Core/DefInjected/ThoughtDef/Thoughts_Situation_Social.xml
Core/DefInjected/ThoughtDef/Thoughts_Situation_Traits.xml
Core/DefInjected/ThoughtDef/Thoughts_Situation_TraitsPerm.xml

#969 Actualize thoughts with gender

---

Royalty/DefInjected/ThoughtDef/Hediffs_BodyParts_Archotech_EmpireRoyal.xml
Royalty/DefInjected/ThoughtDef/Thoughts_Memory_Eating.xml
Royalty/DefInjected/ThoughtDef/Thoughts_Memory_RoomStats.xml
Royalty/DefInjected/ThoughtDef/Thoughts_Memory_Special.xml
Royalty/DefInjected/ThoughtDef/Thoughts_RoyalTitles.xml
Royalty/DefInjected/ThoughtDef/Thoughts_Situation_MusicalInstruments.xml
Royalty/DefInjected/ThoughtDef/Thoughts_Situation_Needs.xml
Royalty/DefInjected/ThoughtDef/Thoughts_Situation_Special.xml

#998 Translate RoyaltyThoughtDef

---

Core/DefInjected/StatDef/Stats_Pawns_General.xml
Core/Keyed/Misc_Gameplay.xml
Core/Keyed/Time.xml
Core/Keyed/WITabs.xml
Core/Keyed/WorkTags.xml

933 keyed 5

---

Royalty/DefInjected/RulePackDef/Script_Hospitality_TextCommon.xml

Fix Script_Hospitality_TextCommon

---

Royalty/DefInjected/QuestScriptDef/Script_Hospitality_Worker.xml
Royalty/DefInjected/QuestScriptDef/Script_Intro_Deserter.xml
Royalty/DefInjected/QuestScriptDef/Script_Intro_Wimp.xml
Royalty/DefInjected/QuestScriptDef/Script_PawnLend.xml
Royalty/DefInjected/RulePackDef/Script_Hospitality_TextCommon.xml

#991 Translate Royalty_QuestScriptDef_6

---

Core/DefInjected/GatheringDef/Gatherings.xml
Royalty/DefInjected/ConceptDef/Concepts_TriggeredModal.xml
Royalty/DefInjected/DutyDef/Duties_Gatherings.xml
Royalty/DefInjected/FactionDef/Faction_Empire.xml
Royalty/DefInjected/GameConditionDef/Buildings_ConditionCausers.xml
Royalty/DefInjected/GatheringDef/Gatherings.xml
Royalty/DefInjected/HairDef/HairsRoyal.xml
Royalty/DefInjected/IncidentDef/Incidents_Map_Special.xml
Royalty/DefInjected/IncidentDef/Incidents_World_Quests.xml
Royalty/DefInjected/JobDef/Jobs_Joy.xml
Royalty/DefInjected/JobDef/Jobs_Misc.xml
Royalty/DefInjected/JoyKindDef/JoyKinds.xml
Royalty/DefInjected/NeedDef/Needs.xml
Royalty/DefInjected/PawnKindDef/PawnKinds_Empire.xml
Royalty/DefInjected/RoyalTitlePermitDef/RoyalPermits_Empire.xml
Royalty/DefInjected/SitePartDef/Buildings_ConditionCausers.xml

#984 Translate Royalty: ConceptDef-PawnKindDef

---

Royalty/DefInjected/TipSetDef/Tips.xml
Royalty/Keyed/Letters.xml
Royalty/Keyed/Messages.xml
Royalty/Keyed/Misc_Gameplay.xml

1001 royalty keyed 2

---

Royalty/Keyed/Alerts.xml
Royalty/Keyed/Dialog_Trees.xml
Royalty/Keyed/Incidents.xml

Alerts 
Incidents
Dialog_Trees

#1000 Translate Keyed1

---

Royalty/DefInjected/RoyalTitleDef/RoyalTitles_Empire.xml

Fix RoyalTitles_Empire

---

Core/DefInjected/TipSetDef/Tips.xml

Change "чиста" -> "чистая" "грязна" -> "грязная"

Fix Tips.xml

---

Core/DefInjected/QuestScriptDef/Script_PrisonerWillingToJoin.xml

Change participle I to indefinite verb

Fix Script_PrisonerWillingToJoin

---

Core/Backstories/Backstories.xml

#1048 Translate Backstories.xml

---

Core/Backstories/Backstories.xml

Close #1052: Logger16-OrnamentMaker56

Translate Backstories.xml

---

Core/DefInjected/HediffDef/Hediffs_Local_Injuries.xml
Core/DefInjected/RecipeDef/Hediffs_Local_Misc.xml
Core/DefInjected/ResearchProjectDef/ResearchProjects_4_MultiAnalyzer.xml
Core/DefInjected/SitePartDef/Manhunters.xml
Core/DefInjected/StatDef/Stats_Abilities.xml
Core/DefInjected/StatDef/Stats_Basics_Special.xml
Core/DefInjected/ThingDef/Buildings_Security.xml
Core/DefInjected/ThingDef/GoJuice.xml
Core/DefInjected/ThoughtDef/Thoughts_Situation_Special.xml
Core/DefInjected/TipSetDef/Tips.xml
Core/DefInjected/TraitDef/Traits_Singular.xml

1077 commit

---

Royalty/DefInjected/AbilityDef/Abilities.xml
Royalty/DefInjected/HediffDef/Hediffs_Psycasts.xml
Royalty/DefInjected/JobDef/Jobs_Misc.xml
Royalty/DefInjected/NeedDef/Needs.xml
Royalty/DefInjected/StatDef/Stats_Pawns_General.xml
Royalty/DefInjected/TipSetDef/Tips.xml

#1103 Translate Royalty-DefInjected for 2645

---

Core/Keyed/Messages.xml

Фикс фразы Вы пробудили механоиды. Т.к. пробуждение сопровождается фразой независимо от того, вы пробудили механоидов передвижением, или они проснулись по таймеру.

Mech wokeup fix

---

Core/DefInjected/GameConditionDef/GameConditions_Misc.xml

Исправила описание умиротворения.

psychic soothe desc fix

---

Royalty/Keyed/Dialogs_Various.xml
Royalty/Keyed/GameplayCommands.xml
Royalty/Keyed/Misc_Gameplay.xml

1117_2653_Keyed_l10n

---

Core/DefInjected/ThingDef/Apparel_Belts.xml
Core/DefInjected/ThingDef/Apparel_Packs.xml
Core/DefInjected/ThingDef/Apparel_Utility.xml
Core/DefInjected/ThingDef/Effecter_Damage.xml
Core/DefInjected/ThingDef/Ethereal_OrbitalStrikes.xml
Core/DefInjected/ThingDef/Items_Artifacts.xml
Core/DefInjected/ThingDef/Mote_Visual.xml
Core/DefInjected/ThingDef/RangedIndustrialGrenades.xml
Core/DefInjected/ThingDef/RangedSpecial.xml

#1132 Core-DefInjected-ThingDef

---

Core/Keyed/Dialogs_Various.xml

#1134 Translate Core/Keyed 2 for 2702

---

Core/DefInjected/RulePackDef/RulePacks_Namers_WorldFeatures.xml
Core/DefInjected/StatDef/Stats_Apparel.xml
Core/DefInjected/StatDef/Stats_Basics_General.xml
Core/DefInjected/StatDef/Stats_Basics_Special.xml
Core/DefInjected/ThingCategoryDef/ThingCategories.xml
Core/DefInjected/ThoughtDef/Thoughts_Memory_Social.xml
Core/DefInjected/TipSetDef/Tips.xml
Core/DefInjected/WorkGiverDef/WorkGivers.xml

#1131 Translate Core/DefInjected 3 for 2702

---

Core/Keyed/Alerts.xml
Core/Keyed/Designators.xml
Core/Keyed/Dialog_StatsReports.xml

#1133 translation Core/Keyed, part 1, for version 2702

---

Core/Keyed/Enums.xml
Core/Keyed/FloatMenu.xml
Core/Keyed/GameplayCommands.xml
Core/Keyed/ITabs.xml
Core/Keyed/Incidents.xml

#1135 Translate Core/Keyed 3 for 2720

---

Core/Keyed/Letters.xml

#1136 Translate Core/Keyed 4 for 2720

---

Core/Keyed/Misc_Gameplay.xml

#1139 Translate Core/Keyed 7 for 2720

---

Royalty/DefInjected/AbilityDef/Abilities.xml

#1140 Translate Royalty/DefInjected 1 for 2720

---

Royalty/DefInjected/FactionDef/Faction_Empire.xml
Royalty/DefInjected/FactionDef/Factions_Misc.xml
Royalty/DefInjected/HediffDef/Hediffs_Psycasts.xml
Royalty/DefInjected/HediffDef/WeaponTraitDefs.xml

#1141 Translate Royalty/DefInjected 2 for 2720

---

Royalty/DefInjected/InteractionDef/Interactions_Social.xml
Royalty/DefInjected/JobDef/Jobs_Misc.xml
Royalty/DefInjected/MentalStateDef/MentalStates_Special.xml
Royalty/DefInjected/PawnKindDef/PawnKinds_Empire.xml
Royalty/DefInjected/PawnKindDef/PawnKinds_Refugee.xml
Royalty/DefInjected/SitePartDef/MechCluster.xml
Royalty/DefInjected/StatDef/Stats_Apparel.xml
Royalty/DefInjected/TipSetDef/Tips.xml
Royalty/DefInjected/WorldObjectDef/WorldObjects.xml

#1143 Translate Royalty/DefInjected 4 for 2720

---

Royalty/DefInjected/ThingDef/Apparel_Packs.xml
Royalty/DefInjected/ThingDef/Items_Exotic.xml

#Translate 1146 Royalty/DefInjected/ThingDef 1 for 2720

---

Royalty/DefInjected/QuestScriptDef/Script_Bestower.xml
Royalty/Keyed/Messages.xml
Royalty/Keyed/Misc_Gameplay.xml

#1177 Fix bestowing ceremony translation

---

Royalty/Keyed/Alerts.xml
Royalty/Keyed/Dialog_StatReports.xml
Royalty/Keyed/Dialogs_Various.xml
Royalty/Keyed/GameplayCommands.xml
Royalty/Keyed/ITabs.xml
Royalty/Keyed/Letters.xml

1150 royalty keyed 1

---

Royalty/DefInjected/ThoughtDef/Thoughts_Memory_Death.xml
Royalty/DefInjected/ThoughtDef/Thoughts_Memory_Misc.xml
Royalty/DefInjected/ThoughtDef/Thoughts_Memory_Special.xml
Royalty/DefInjected/ThoughtDef/Thoughts_Situation_Special.xml
Royalty/DefInjected/ThoughtDef/WeaponTraitDefs.xml

#1148 Royalty/DefInjected/ThoughtDef, for version 2702

---

Royalty/DefInjected/ThoughtDef/WeaponTraitDefs.xml
Royalty/DefInjected/WeaponTraitDef/WeaponTraitDefs.xml

#1149 Translate Royalty weapon traits

---

Core/Keyed/Menus_Main.xml

#1138 Core/Keyed, part 6 translation

---

Core/Backstories/Backstories.xml

PamperedLordling37-RoyalBastard3
Close #1053

#1053 Translate Backstories.xml

---

Core/Backstories/Backstories.xml

#1054 Translate Backstories.xml (RoyalCook18-Spymaster41)

---

Core/Backstories/Backstories.xml

Update translation of a backstories added in .2747: <OrphanedAcrobat84>, <MercenaryCaptain56>, <ArtSlave57>, <ModDesigner85>.

Update Backstories translation

---

Core/Backstories/Backstories.xml

Fix for Backstories.xml 

---

Core/Backstories/Backstories.xml

Happy New Year! Fixed tenses (lines 2000-3003)

Fix for Backstories.xml pt.3

---

Core/Backstories/Backstories.xml

Fixed tenses and other (lines 3000-4000)

Fix for Backstories.xml pt.4

---

Core/DefInjected/InstructionDef/Instructions.xml
Core/DefInjected/InteractionDef/Interactions_Animal.xml
Core/DefInjected/InteractionDef/Interactions_Social.xml
Core/DefInjected/IssueDef/Precepts_AteNutrientPaste.xml
Core/DefInjected/IssueDef/Precepts_Cannibalism.xml
Core/DefInjected/IssueDef/Precepts_Corpses.xml
Core/DefInjected/IssueDef/Precepts_InsectMeat.xml
Core/DefInjected/IssueDef/Precepts_Lovin.xml
Core/DefInjected/IssueDef/Precepts_MarriageName.xml
Core/DefInjected/IssueDef/Precepts_OrganUse.xml
Core/DefInjected/IssueDef/Precepts_PrisonerExecution.xml
Core/DefInjected/IssueDef/Precepts_Ritual.xml
Core/DefInjected/IssueDef/Precepts_Slavery.xml
Core/DefInjected/IssueDef/Precepts_SpouseCount.xml
Core/DefInjected/JobDef/Jobs_Caravan.xml
Core/DefInjected/JobDef/Jobs_Misc.xml
Core/DefInjected/JobDef/Jobs_Work.xml
Core/DefInjected/JoyKindDef/JoyKinds.xml

#1205 
Translate pt. 4 of Core/Definjected

3056 Core/Definjected-4

---

Core/DefInjected/DifficultyDef/Difficulties.xml
Core/DefInjected/ExpansionDef/ExpansionDefs.xml
Core/DefInjected/FactionDef/Factions_Hidden.xml
Core/DefInjected/FactionDef/Factions_Misc.xml

#1203 
Translate pt. 2 of Core/Definjected

3056 Core/DefInjected-2

---

Core/DefInjected/BeardDef/BeardDefs.xml
Core/DefInjected/BodyDef/Bodies_Mechanoid.xml
Core/DefInjected/ConceptDef/Concepts_NotedOpportunistic.xml
Core/DefInjected/CultureDef/Cultures.xml
Core/DefInjected/DamageDef/Damages_MeleeWeapon.xml
Core/DefInjected/DamageDef/Damages_Misc.xml

Close #1202 
Translate pt.1 of Core/Definjected

3056 Core/Definjected-1

---

Core/Backstories/Backstories.xml
Core/Keyed/Alerts.xml
Core/Keyed/Credits.xml
Core/Keyed/Designators.xml
Core/Keyed/Dialog_StatsReports.xml
Core/Keyed/Dialogs_Various.xml

Translate Core Keyed, part 1

---

Core/DefInjected/OrderedTakeGroupDef/OrderedTakeGroupDefs.xml
Core/DefInjected/PawnColumnDef/PawnColumns_Checkbox.xml
Core/DefInjected/PawnColumnDef/PawnColumns_Icon.xml
Core/DefInjected/PawnColumnDef/PawnColumns_Misc.xml
Core/DefInjected/PawnColumnDef/PawnColumns_Text.xml
Core/DefInjected/PawnKindDef/PawnKinds_Breach.xml
Core/DefInjected/PawnKindDef/Races_Animal_BigBirds.xml
Core/DefInjected/PawnKindDef/Races_Animal_CatGroup.xml
Core/DefInjected/PawnKindDef/Races_Animal_ChickenGroup.xml
Core/DefInjected/PawnKindDef/Races_Animal_CowGroup.xml
Core/DefInjected/PawnKindDef/Races_Animal_MiscGroup.xml
Core/DefInjected/PawnKindDef/Races_Animal_PigGroup.xml
Core/DefInjected/PawnKindDef/Races_Animal_SheepGroup.xml
Core/DefInjected/PawnKindDef/Races_Animal_SquirrelGroup.xml
Core/DefInjected/PawnKindDef/Races_Animal_WargGroup.xml
Core/DefInjected/PawnKindDef/Races_Animal_WildCanines.xml
Core/DefInjected/PawnsArrivalModeDef/PawnsArrivalModes.xml
Core/DefInjected/PlaceDef/Places.xml

Close #1207  Translate Core/DefInjected-6

3056 Core/DefInjected-6

---

Core/DefInjected/GoodwillSituationDef/GoodwillSituations_Misc.xml
Core/DefInjected/HairDef/HairsGeneral.xml
Core/DefInjected/HediffDef/Hediffs_Local_Misc.xml
Core/DefInjected/HediffDef/Hediffs_Local_TerrainAttacks.xml
Core/DefInjected/HistoryEventDef/GoodwillEvents_Diplomatic.xml
Core/DefInjected/HistoryEventDef/GoodwillEvents_Misc.xml
Core/DefInjected/HistoryEventDef/GoodwillEvents_Pawns.xml
Core/DefInjected/HistoryEventDef/GoodwillEvents_Quests.xml
Core/DefInjected/HistoryEventDef/GoodwillEvents_World.xml
Core/DefInjected/HistoryEventDef/HistoryEventDefs.xml
Core/DefInjected/HistoryEventDef/PawnRelations_Misc.xml
Core/DefInjected/HistoryEventDef/Precepts_AteNutrientPaste.xml
Core/DefInjected/HistoryEventDef/Precepts_Cannibalism.xml
Core/DefInjected/HistoryEventDef/Precepts_Corpses.xml
Core/DefInjected/HistoryEventDef/Precepts_InsectMeat.xml
Core/DefInjected/HistoryEventDef/Precepts_Lovin.xml
Core/DefInjected/HistoryEventDef/Precepts_MarriageName.xml
Core/DefInjected/HistoryEventDef/Precepts_OrganUse.xml
Core/DefInjected/HistoryEventDef/Precepts_PrisonerExecution.xml
Core/DefInjected/HistoryEventDef/Precepts_Slavery.xml
Core/DefInjected/HistoryEventDef/Precepts_SpouseCount.xml
Core/DefInjected/IncidentDef/Incidents_Map_Misc.xml

Close #1204 
Translate pt. 3 of Core/Definjected

3056 Core/DefInjected-3

---

Core/DefInjected/KeyBindingCategoryDef/KeyBindingCategories.xml
Core/DefInjected/KeyBindingDef/ImpliedDefs.xml
Core/DefInjected/MainButtonDef/MainButtons.xml
Core/DefInjected/MentalStateDef/MentalStates_Special.xml
Core/DefInjected/NeedDef/Needs.xml

Close #1206  
Translate pt. 5 of Core/Definjected

3056 Core/Definjected-5

---

Core/DefInjected/StatDef/Stats_Basics_Special.xml
Core/DefInjected/StatDef/Stats_Pawns_General.xml
Core/DefInjected/StatDef/Stats_Pawns_Social.xml
Core/DefInjected/StatDef/Stats_Pawns_WorkGeneral.xml
Core/DefInjected/StatDef/Stats_Weapons_Melee.xml
Core/DefInjected/StyleItemCategoryDef/StyleItemCategoryDefs.xml
Core/DefInjected/TaleDef/Tales_Job.xml
Core/DefInjected/TattooDef/TattooDefs.xml
Core/DefInjected/TerrainDef/Terrain_Floors.xml

Close #1210 Translate Core/DefInjected-9

3056 Core/DefInjected-9

---

Core/DefInjected/ResearchProjectDef/ResearchProjects_3_Microelectronics.xml
Core/DefInjected/RitualOutcomeEffectDef/Ritual_Outcomes.xml
Core/DefInjected/RulePackDef/Faction_Empire.xml
Core/DefInjected/RulePackDef/Places.xml
Core/DefInjected/RulePackDef/RulePacks_Namers_People.xml
Core/DefInjected/SpecialThingFilterDef/SpecialThingFilters.xml
Core/DefInjected/StatCategoryDef/StatCategories.xml

Close #1209  Translate Core/DefInjected-8

3056 Core/DefInjected-8

---

Royalty/DefInjected/TipSetDef/Tips.xml
Royalty/DefInjected/TransportShipDef/TransportShipDefs.xml

Close #1222 Translate Royalty/DefInjected-5

3056 Royalty/DefInjected-5

---

Core/DefInjected/TrainabilityDef/TrainabilityDefs.xml
Core/DefInjected/TraitDef/Traits_Singular.xml
Core/DefInjected/WeaponClassDef/WeaponClassDefs.xml
Core/DefInjected/WorkGiverDef/WorkGivers.xml

Close #1212  Translate Core/DefInjected-11

3056 Core/DefInjected-11

---

Royalty/Keyed/Alerts.xml
Royalty/Keyed/Dialog_StatReports.xml
Royalty/Keyed/Dialogs_Various.xml

3056-royalty-keyed-1

---

Ideology/Keyed/Alerts.xml
Ideology/Keyed/Designators.xml

Translation update
Issue #1245 persists

1245 ideology keyed 1

---

Ideology/Keyed/Dialogs_Various.xml

Close #1246 Translate Ideology/Keyed-2

3067 Ideology/Keyed-2

---

Ideology/Keyed/Alerts.xml
Ideology/Keyed/Dialog_StatsReports.xml
Ideology/Keyed/FloatMenu.xml
Ideology/Keyed/GameplayCommands.xml
Ideology/Keyed/ITabs.xml

Close #1247  Translate Ideology/Keyed-3

3067 Ideology/Keyed-3

---

Ideology/Keyed/Letters.xml

Close #1248  Translate Ideology/Keyed4

3067 Ideology/Keyed4

---

Ideology/DefInjected/IssueDef/Precepts_Skullspike.xml
Ideology/DefInjected/IssueDef/Precepts_Transhumanism.xml
Ideology/Keyed/Dialogs_Various.xml
Ideology/Keyed/FloatMenu.xml
Ideology/Keyed/Misc_Gameplay.xml

#1250 Translate Keyed/Misc_Gameplay.xml

---

Ideology/DefInjected/IdeoStoryPatternDef/RulePacks_Ideo_Description.xml
Ideology/DefInjected/MemeDef/Memes_GroupRelation.xml
Ideology/DefInjected/MemeDef/Memes_Misc.xml
Ideology/Keyed/MainTabs.xml

Не закрывать #1278 после мерджа

1278 ideology def injected meme def 3

---

Ideology/DefInjected/MemeDef/Memes_Misc.xml

#1278 Translate FleshPurity, HighLife and Nudism memes

---

Ideology/DefInjected/GoodwillSituationDef/GoodwillSituations_MemeCompatibility.xml
Ideology/DefInjected/MemeDef/Memes_Misc.xml

#1278 Translate PainIsVirtue, Proselytizer, Raider

---

Ideology/DefInjected/MemeDef/Memes_Misc.xml

#1278 Translate Tunneler

---

Ideology/DefInjected/MemeDef/Memes_Structures_Basic.xml
Ideology/DefInjected/MemeDef/Memes_Structures_OriginsReligious.xml

#1279 Translate Memes_Structures_Basic.xml

---

Ideology/DefInjected/MemeDef/Memes_Primacy.xml

#1279 Translate HumanPrimacy and NaturePrimacy

---

Core/DefInjected/IssueDef/Precepts_AteNutrientPaste.xml
Core/DefInjected/IssueDef/Precepts_MarriageName.xml
Ideology/DefInjected/IssueDef/Precepts_RitualSeats.xml
Ideology/DefInjected/PreceptDef/Precepts_OrganUse.xml
Ideology/DefInjected/PreceptDef/Precepts_Pain.xml
Ideology/DefInjected/PreceptDef/Precepts_PrisonerExecution.xml
Ideology/DefInjected/PreceptDef/Precepts_Proselytizing.xml
Ideology/DefInjected/PreceptDef/Precepts_Raiders.xml
Ideology/DefInjected/PreceptDef/Precepts_Ranching.xml
Ideology/DefInjected/PreceptDef/Precepts_Relics.xml
Ideology/DefInjected/PreceptDef/Precepts_Research.xml
Ideology/DefInjected/PreceptDef/Precepts_Ritual.xml
Ideology/DefInjected/PreceptDef/Precepts_RitualSeats.xml
Ideology/DefInjected/PreceptDef/Precepts_Role.xml
Ideology/DefInjected/PreceptDef/Precepts_RoughLiving.xml
Ideology/DefInjected/PreceptDef/Precepts_Scarification.xml
Ideology/DefInjected/PreceptDef/Precepts_Skullspike.xml
Ideology/DefInjected/PreceptDef/Precepts_Slavery.xml
Ideology/DefInjected/PreceptDef/Precepts_SmallSpaces.xml
Ideology/DefInjected/PreceptDef/Precepts_SpouseCount.xml
Ideology/DefInjected/PreceptDef/Precepts_Transhumanism.xml
Ideology/DefInjected/PreceptDef/Precepts_TreeCutting.xml
Ideology/DefInjected/PreceptDef/Precepts_Trees.xml
Ideology/DefInjected/PreceptDef/Precepts_Weapons.xml
Ideology/DefInjected/PreceptDef/Precepts_WorkDrive.xml

Close #1282 + minor adjustments

Ideology/DefInjected/PreceptDef pt. 2 (edited)

---

Ideology/DefInjected/ThingDef/Buildings_Ancient_Indoors.xml
Ideology/DefInjected/ThingDef/Buildings_Ancient_Outdoors.xml

Два файла с описаниями старого хлама, были сделаны для перевода на русский мода Vanilla Ideology Expanded - Memes and Structures. Текстовые строки идентичны таким же из DLC Ideology

Древний хлам

---

Ideology/DefInjected/ThoughtDef/Precepts_Charity.xml

Translate Precepts_Charity.xml
Close #1292

Ideology/DefInjected/ThoughtDef, part 3 

---

Core/DefInjected/ThoughtDef/Thoughts_Situation_General.xml
Ideology/DefInjected/ThoughtDef/Precepts_Cannibalism.xml

Ideology/DefInjected/ThoughtDef, part 2 

---

Ideology/DefInjected/ThoughtDef/Precepts_InsectMeat.xml

Описание состояний после употребления мяса насекомых

#1294 Add insect meat description

---

Ideology/DefInjected/ThoughtDef/Precepts_Ranching.xml
Ideology/DefInjected/ThoughtDef/Precepts_Relics.xml
Ideology/DefInjected/ThoughtDef/Precepts_Scarification.xml
Ideology/DefInjected/ThoughtDef/Precepts_Skullspike.xml

#1295 Translate Ieology ThoughtDef 6, part 2

---

Ideology/DefInjected/ThoughtDef/Precepts_Mining.xml
Ideology/DefInjected/ThoughtDef/Precepts_Nudity.xml

#1294 Translate thoughts about Mining, Nudity

---

Core/Backstories/Backstories.xml

fixed translation for Backstories.xml (lines 4k-5k)
yada-yada

Fix for Backstories.xml pt.5 

---

Core/DefInjected/ColorDef/ColorDefs.xml

close #1398 Translated file ColorsDefs.xml from <Structure_Auburn.label> to </Structure_YellowPastel.label>

Translated File name

---

Core/DefInjected/ThingCategoryDef/ThingCategories.xml
Core/DefInjected/ThingDef/Apparel_Packs.xml
Core/DefInjected/ThingDef/Buildings_Furniture.xml
Core/DefInjected/ThingDef/Buildings_Mech.xml
Core/DefInjected/ThingDef/Buildings_Security_Turrets.xml
Core/DefInjected/ThingDef/ImpliedDefs.xml
Core/DefInjected/ThingDef/Items_Unfinished.xml
Core/DefInjected/ThingDef/Races_Mechanoid.xml

translated TODOs

---

Core/DefInjected/BackstoryDef/Special.xml

Первая половина по соглашению:
https://github.com/Ludeon/RimWorld-ru/issues/1397#issuecomment-1287766361

Translated first half of backstory

---

Core/DefInjected/BackstoryDef/Marshal_Adult.xml
Core/DefInjected/BackstoryDef/Mate_Child.xml
Core/DefInjected/BackstoryDef/Sadist_Adult.xml
Core/DefInjected/BackstoryDef/Sadist_Child.xml

Close #1400: Add translation for 4 backstories

Translated #1400 Backstories part 2

---

Core/Keyed/Alerts.xml
Core/Keyed/Designators.xml
Core/Keyed/Dialog_StatsReports.xml
Core/Keyed/Dialogs_Various.xml
Core/Keyed/Enums.xml

Translate #1419 Keyed 1 

---

Core/DefInjected/ConceptDef/Concepts_NotedOpportunistic.xml
Core/DefInjected/ConceptDef/Concepts_NotedSelfshow.xml
Core/DefInjected/DebugTabMenuDef/DebugTabMenuDefs.xml
Core/DefInjected/HediffDef/Hediffs_Global_Misc.xml
Core/DefInjected/HediffDef/Hediffs_Local_Infections.xml
Core/DefInjected/HediffDef/Hediffs_Local_Misc.xml
Core/DefInjected/HistoryEventDef/GoodwillEvents_Pawns.xml
Core/DefInjected/JobDef/Jobs_Work.xml
Core/DefInjected/KeyBindingDef/KeyBindings.xml
Core/DefInjected/PawnKindDef/Races_Mechanoid.xml
Core/DefInjected/RecipeDef/Recipes_Meals.xml
Core/DefInjected/ResearchProjectDef/ResearchProjects_2_Electricity.xml
Core/DefInjected/ResearchProjectDef/ResearchProjects_4_MultiAnalyzer.xml
Core/DefInjected/SpecialThingFilterDef/SpecialThingFilters.xml

Translate #1403 DefInjected: misc

---

Core/Keyed/FloatMenu.xml
Core/Keyed/GameplayCommands.xml
Core/Keyed/ITabs.xml
Core/Keyed/Letters.xml
Core/Keyed/Menus_Main.xml
Core/Keyed/Messages.xml

Translate #1420 Keyed 2

---

Core/DefInjected/BackstoryDef/Gambler_Adult.xml
Core/DefInjected/BackstoryDef/Gambler_Child.xml
Core/DefInjected/BackstoryDef/InsectsRelated_Child.xml

close #1399
Translate backstories from Definjected/BackstoryDef starting from Gambler_adult.xml to InsectsRelated_Child.xml

Translate #1399 Gambler to InsectChild

---

Biotech/DefInjected/HistoryEventDef/HistoryEventDefs.xml
Biotech/DefInjected/IncidentDef/Incidents_Map_Misc.xml
Biotech/DefInjected/IncidentDef/Incidents_Map_Special.xml
Biotech/DefInjected/IncidentDef/Incidents_Map_Threats.xml
Biotech/DefInjected/JobDef/Jobs_Childcare.xml
Biotech/DefInjected/JobDef/Jobs_Learning.xml
Biotech/DefInjected/JobDef/Jobs_Misc.xml
Biotech/DefInjected/JobDef/Jobs_Play.xml
Biotech/DefInjected/JobDef/Jobs_Work.xml

Translate new xmls
Close #1435

Translate  #1435 Biotech DefInjected 4

---

Biotech/DefInjected/BeardDef/BeardDefs.xml
Biotech/DefInjected/BodyDef/Bodies_Mechanoid_Heavy.xml
Biotech/DefInjected/BodyDef/Bodies_Mechanoid_Light.xml
Biotech/DefInjected/BodyDef/Bodies_Mechanoid_Medium.xml
Biotech/DefInjected/BodyDef/Bodies_Mechanoid_Superheavy.xml
Biotech/DefInjected/BodyPartDef/BodyParts_Mechanoid.xml
Biotech/DefInjected/BodyPartGroupDef/BodyPartGroups.xml
Core/DefInjected/BeardDef/BeardDefs.xml

Translate xmls, modify BeardDefs.xml
Close #1433

Translate #1433 Biotech DefInjected 2 

---

Biotech/DefInjected/AbilityDef/Abilities.xml
Biotech/DefInjected/AbilityDef/Hediffs_Mechanitor.xml

Close #1432: Add translation of abilites and hediffs

Translated #1432-Biotech-DefIjected-1

---

Biotech/DefInjected/ThingDef/Buildings_Misc.xml

Translated #1444-Biotech-DefInjected-ThingDef-1

---

Biotech/DefInjected/ThingDef/Apparel_Child.xml
Biotech/DefInjected/ThingDef/Apparel_Headgear.xml
Biotech/DefInjected/ThingDef/Apparel_Mech.xml
Biotech/DefInjected/ThingDef/Apparel_Packs.xml
Biotech/DefInjected/ThingDef/Apparel_Various.xml

Close #1446: Add translations for all files

Translate #1446-Biotech-DefInjected-ThingDef-3

---

Biotech/DefInjected/ThingDef/Items_Resource_Manufactured.xml
Biotech/DefInjected/ThingDef/Items_Resources_RawPlant.xml

Translate #1445 Biotech DefInjected ThingDef 2

---

Core/DefInjected/ThingDef/Items_Resource_AnimalProduct.xml

Как вариант "Можно использовать для кормления младенцев."

Milk description change

---

Biotech/DefInjected/PawnKindDef/PawnKinds_Impid.xml
Biotech/DefInjected/PawnKindDef/PawnKinds_Pigskin.xml
Biotech/DefInjected/PawnKindDef/PawnKinds_Special.xml
Biotech/DefInjected/PawnKindDef/PawnKinds_Waster.xml
Biotech/DefInjected/PawnKindDef/PawnKinds_Yttakin.xml
Biotech/DefInjected/PawnKindDef/Races_Animal_Pollution.xml
Biotech/DefInjected/PawnKindDef/Races_Mechanoids_Heavy.xml
Biotech/DefInjected/PawnKindDef/Races_Mechanoids_Light.xml
Biotech/DefInjected/PawnKindDef/Races_Mechanoids_Medium.xml
Biotech/DefInjected/PawnKindDef/Races_Mechanoids_SuperHeavy.xml

Translate  #1437 Biotech DefInjected 6 

---

Biotech/DefInjected/PawnRelationDef/PawnRelations_FamiltyByBlood.xml
Biotech/DefInjected/PawnRelationDef/PawnRelations_Misc.xml
Biotech/DefInjected/PreceptDef/Precepts_Rituals.xml
Biotech/DefInjected/PrisonerInteractionModeDef/PrisonerInteractionMode.xml
Biotech/DefInjected/RaidAgeRestrictionDef/RaidAgeRestrictions.xml
Biotech/DefInjected/RitualBehaviorDef/Ritual_Behaviors.xml
Biotech/DefInjected/RitualPatternDef/Ritual_Patterns.xml
Biotech/DefInjected/RoomRoleDef/RoomRoles.xml

Translate #1438 Biotech DefInjected 7

---

Biotech/DefInjected/StatDef/Stats_Buildings_Special.xml
Biotech/DefInjected/StatDef/Stats_Misc.xml
Biotech/DefInjected/StatDef/Stats_Pawns_Combat.xml
Biotech/DefInjected/StatDef/Stats_Pawns_General.xml
Biotech/DefInjected/StatDef/Stats_Pawns_WorkGeneral.xml

Translate #1441 Biotech DefInjected 10

---

Biotech/DefInjected/StyleItemCategoryDef/BeardDefs.xml
Biotech/DefInjected/TipSetDef/Tips.xml
Biotech/DefInjected/ToolCapacityDef/ToolCapacityDefs.xml
Biotech/DefInjected/TraitDef/Traits.xml
Biotech/DefInjected/TransportShipDef/TransportShipDefs.xml
Biotech/DefInjected/WorkTypeDef/WorkTypes.xml

Translate #1442 Biotech DefInjected 11

---

Biotech/DefInjected/ThoughtDef/GeneDefs_Sanguophage.xml
Biotech/DefInjected/ThoughtDef/Thoughts_Memory_Childcare.xml
Biotech/DefInjected/ThoughtDef/Thoughts_Memory_Death.xml
Biotech/DefInjected/ThoughtDef/Thoughts_Memory_Eating.xml
Biotech/DefInjected/ThoughtDef/Thoughts_Memory_Social.xml
Biotech/DefInjected/ThoughtDef/Thoughts_Memory_Special.xml
Biotech/DefInjected/ThoughtDef/Thoughts_Situation_Needs.xml
Biotech/DefInjected/ThoughtDef/Thoughts_Situation_Social.xml
Biotech/DefInjected/ThoughtDef/Thoughts_Situation_Special.xml
Biotech/DefInjected/ThoughtDef/Thoughts_Situational_Children.xml
Biotech/DefInjected/ThoughtDef/WeaponTraitDefs.xml

Close #1460 
Не все мысли удалось воспроизвести для проверки в игре, например не понимаю как вызвать мысль "убил родную мать" при убийстве возникает обычная мысль "Моя мать, имя" мертва

Translate #1460 Biotech ThoughtDefs

---

Biotech/Keyed/Messages.xml

Translate #1469 Biotech Keyed Messages

---

Core/DefInjected/PawnKindDef/Races_Mechanoid.xml

fix : Core/DefInjected/PawnKind_Def/Races_Mechanoid.xml

---

Biotech/Keyed/ITabs.xml

Translate #1467 Biotech Keyed ITabs

---

Biotech/DefInjected/ThoughtDef/Precepts_Bloodfeeders.xml
Biotech/DefInjected/ThoughtDef/Precepts_ChildLabor.xml
Biotech/DefInjected/ThoughtDef/Precepts_GrowthVat.xml
Biotech/DefInjected/ThoughtDef/Precepts_Xenotype.xml
Biotech/DefInjected/ThoughtDef/Thoughts_Situation_Genes.xml

added missing thoughts from Ideology-Biotech crosspatch

---

Biotech/DefInjected/ThingDef/Plants_Special.xml
Biotech/DefInjected/ThingDef/Plants_Wild_General.xml
Biotech/DefInjected/ThingDef/Races_Animal_Pollution.xml

Translate #1452 Biotech DefInjected ThingDef 9 

---

Biotech/DefInjected/Recipe/Hediffs_BodyParts_Detoxifier.xml
Biotech/DefInjected/Recipe/Recipes_Food.xml
Biotech/DefInjected/Recipe/Recipes_MechGestator_Heavy.xml
Biotech/DefInjected/Recipe/Recipes_MechGestator_Light.xml
Biotech/DefInjected/Recipe/Recipes_MechGestator_Medium.xml
Biotech/DefInjected/Recipe/Recipes_MechGestator_SuperHeavy.xml
Biotech/DefInjected/Recipe/Recipes_MechResurrection.xml
Biotech/DefInjected/Recipe/Recipes_Surgery_Misc.xml

Translate #1458 Biotech DefInjected Recipe

---

Biotech/DefInjected/ThingDef/RangedIndustrial.xml
Biotech/DefInjected/ThingDef/RangedMechanoid_Heavy.xml
Biotech/DefInjected/ThingDef/RangedMechanoid_Light.xml
Biotech/DefInjected/ThingDef/RangedMechanoid_Medium.xml

Translate #1450 Biotech DefInjected ThingDef 7

---

Biotech/DefInjected/GeneCategoryDef/GeneCategoryDefs.xml
Biotech/DefInjected/GeneDef/GeneDefs_Abilities.xml
Biotech/DefInjected/GeneDef/GeneDefs_Cosmetic.xml
Biotech/DefInjected/GeneDef/GeneDefs_Endogenes.xml
Biotech/DefInjected/GeneDef/GeneDefs_Health.xml
Biotech/DefInjected/GeneDef/GeneDefs_Misc.xml
Biotech/DefInjected/GeneDef/GeneDefs_Sanguophage.xml
Biotech/DefInjected/GeneDef/GeneDefs_Spectrum.xml
Biotech/DefInjected/GeneTemplateDef/GeneTemplateDefs.xml

Close #1455 
Проверено в игре.
Слово "чувствительность" не влезает в строчку, нужно попросить разрабов увеличить лимит на один символ.
Примерный лимит 14 символов.
После перевода и проверки некоторые названия были изменены и разбиты из многокоренных слов в несколько слов, чтобы всё влезало и было красиво.

Translate #1455 Biotech DefInjected-Gene

---

Biotech/DefInjected/HediffDef/Buildings_Deathrest.xml
Biotech/DefInjected/HediffDef/Buildings_Misc.xml
Biotech/DefInjected/HediffDef/Hediffs_BodyParts_Detoxifier.xml
Biotech/DefInjected/HediffDef/Hediffs_Global_Misc.xml
Biotech/DefInjected/HediffDef/Hediffs_Local_Injuries.xml
Biotech/DefInjected/HediffDef/Hediffs_Local_Misc.xml
Biotech/DefInjected/HediffDef/Hediffs_Mechanitor.xml
Biotech/DefInjected/HediffDef/Hediffs_Mechs.xml
Biotech/DefInjected/HediffDef/Hediffs_Various.xml

Translate #1456 Biotech DefInjected-Hediff

---

Biotech/DefInjected/NeedDef/Needs.xml
Biotech/Keyed/Misc_Gameplay.xml

Translate #1466 Biotech Keyed Gameplay

---

Biotech/DefInjected/InteractionDef/Interactions_Social.xml
Biotech/DefInjected/RulePackDef/Interactions_Social.xml
Ideology/Keyed/Misc_Gameplay.xml

Biothech Interactions

---

Biotech/DefInjected/DamageDef/Damages_Stun.xml
Biotech/DefInjected/GeneDef/GeneDefs_Misc.xml
Biotech/DefInjected/GeneDef/GeneDefs_Spectrum.xml
Biotech/DefInjected/GeneTemplateDef/GeneTemplateDefs.xml
Biotech/DefInjected/HediffDef/Hediffs_Global_Misc.xml
Biotech/DefInjected/HediffDef/Hediffs_Various.xml
Biotech/DefInjected/ThingDef/Races_Mechanoids_Medium.xml
Biotech/DefInjected/ThingDef/RangedMechanoid_Medium.xml
Biotech/Keyed/Messages.xml
Biotech/Keyed/Misc_Gameplay.xml

Обновление перевода за изменившимся оригиналом

Biotech updates

---

Biotech/Keyed/GameplayCommands.xml
Biotech/Keyed/MainTabs.xml
Biotech/Keyed/Menus_Main.xml
Biotech/Keyed/ScenParts.xml
Biotech/Keyed/WITabs.xml

Translate #1461  Biotech keyed 1

#1461 Biotech keyed 1

---

Biotech/DefInjected/ResearchProjectDef/ResearchProjects_Mechanitor.xml
Biotech/DefInjected/ResearchProjectDef/ResearchProjects_Misc.xml
Biotech/DefInjected/RitualOutcomeEffectDef/Ritual_Outcomes.xml
Biotech/DefInjected/RoomStatDef/RoomStats.xml

close #1439
Translate Biotech Definjected, part 8, files ResearchPrejects_Mechanitor.xml, ResearchPrejects_Misc.xml, Ritual_Outcomes.xml, RoomStats.xml

close #1439 , Biotech DefInjected 8

---

Biotech/Keyed/Dialogs_Various.xml

Translate Dialogs.xml from Biotech/Keyed

close #1464

---

Biotech/DefInjected/TaleDef/Tales_DoublePawns.xml
Biotech/DefInjected/TaleDef/Tales_Incident.xml

#1443 Tales

---

Core/DefInjected/IssueDef/Precepts_MarriageName.xml
Core/DefInjected/PreceptDef/Precepts_AteNutrientPaste.xml
Core/DefInjected/PreceptDef/Precepts_Corpses.xml
Ideology/DefInjected/IssueDef/Precepts_Mining.xml
Ideology/DefInjected/PreceptDef/Precepts_AteNutrientPaste.xml
Ideology/DefInjected/PreceptDef/Precepts_Comfort.xml
Ideology/DefInjected/PreceptDef/Precepts_Corpses.xml
Ideology/DefInjected/PreceptDef/Precepts_MarriageName.xml
Ideology/DefInjected/PreceptDef/Precepts_Mining.xml
Ideology/DefInjected/PreceptDef/Precepts_Nudity.xml
Ideology/DefInjected/PreceptDef/Precepts_PrisonerExecution.xml
Ideology/DefInjected/PreceptDef/Precepts_Research.xml
Ideology/DefInjected/PreceptDef/Precepts_RoughLiving.xml
Ideology/DefInjected/PreceptDef/Precepts_Scarification.xml
Ideology/DefInjected/PreceptDef/Precepts_SmallSpaces.xml

Изменил формулировку некоторых принципов, для лучшей согласованности

Fix Precept forms

---

Biotech/DefInjected/MemeDef/Memes_Bloodfeeding.xml
Ideology/DefInjected/IdeoStoryPatternDef/RulePacks_Ideo_Description.xml
Ideology/DefInjected/MemeDef/Memes_GenderSupremacy.xml
Ideology/DefInjected/MemeDef/Memes_GroupRelation.xml
Ideology/DefInjected/MemeDef/Memes_Individualism.xml
Ideology/DefInjected/MemeDef/Memes_Misc.xml
Ideology/DefInjected/MemeDef/Memes_Primacy.xml

Четвёртая часть исправлений: _TheistMyth_.

Ideoligion narrative changes Pt. 4

---

Core/DefInjected/BackstoryDef/Offworld_Glitterworld_Adult.xml
Core/DefInjected/BackstoryDef/Offworld_Medieval_Adult.xml
Core/DefInjected/BackstoryDef/Offworld_Nonspecific_Adult.xml
Core/DefInjected/BackstoryDef/Offworld_Specific_Adult.xml
Core/DefInjected/BackstoryDef/Solid_Adult.xml
Core/DefInjected/BackstoryDef/Solid_Child.xml
Royalty/DefInjected/BackstoryDef/ImperialFighter_Adult.xml

Быстрые апдейты предысторий: удаления, исправления и прочее

backstories changes

---

Core/Keyed/Misc_Gameplay.xml

Третий реквест по Keyed-строкам
Close #1637

Core 1.5 Keyed 3

---

Anomaly/Keyed/ITabs.xml
Biotech/DefInjected/GeneDef/GeneDefs_Spectrum.xml
Biotech/Keyed/Misc_Gameplay.xml
Core/DefInjected/PawnCapacityDef/PawnCapacity.xml
Core/DefInjected/PawnRenderTreeDef/PawnRenderTreeDefs.xml
Core/DefInjected/PawnsArrivalModeDef/PawnsArrivalModes.xml
Core/DefInjected/PrisonerInteractionModeDef/PrisonerInteractionMode.xml
Core/DefInjected/RaidStrategyDef/RaidStrategies_Basic.xml
Core/DefInjected/RaidStrategyDef/RaidStrategies_Breach.xml
Core/DefInjected/RecipeDef/Hediffs_BodyParts_Bionic.xml
Core/DefInjected/RecipeDef/Recipes_Production.xml
Core/DefInjected/ResearchTabDef/ResearchTabs.xml
Core/DefInjected/RoomStatDef/RoomStats.xml
Core/DefInjected/SpecialThingFilterDef/SpecialThingFilters.xml
Core/DefInjected/StatDef/Stats_Basics_Special.xml
Core/DefInjected/StatDef/Stats_Building_Special.xml
Core/DefInjected/StatDef/Stats_Pawns_Combat.xml
Core/DefInjected/StatDef/Stats_Pawns_General.xml
Core/DefInjected/StatDef/Stats_Pawns_WorkGeneral.xml
Core/DefInjected/SurgeryOutcomeEffectDef/SurgeryOutcomeEffectDefs.xml
Core/DefInjected/TaleDef/Tales_SinglePawn.xml
Core/DefInjected/TipSetDef/Tips.xml
Ideology/Keyed/Dialogs_Various.xml
Royalty/DefInjected/ThingDef/Items_Exotic.xml
Royalty/DefInjected/TipSetDef/Tips.xml

Перевёл DefInjected 2
Исправил отдельным коммитом ещё пару мелких ошибок, не связанных с 1.5
Close #1642

1.5 definjected 2

---

Biotech/DefInjected/HediffDef/Hediffs_BodyParts_Detoxifier.xml
Core/DefInjected/HediffDef/Hediffs_BodyParts_Archotech.xml
Core/DefInjected/HediffDef/Hediffs_BodyParts_Bionic.xml
Core/DefInjected/HediffDef/Hediffs_BodyParts_Medieval.xml
Core/DefInjected/HediffDef/Hediffs_BodyParts_Prosthetic.xml
Core/DefInjected/ThingDef/Hediffs_BodyParts_Archotech.xml
Core/DefInjected/ThingDef/Hediffs_BodyParts_Bionic.xml
Core/DefInjected/ThingDef/Hediffs_BodyParts_Prosthetic.xml
Royalty/DefInjected/HediffDef/Hediffs_BodyParts_Archotech_EmpireRoyal.xml
Royalty/DefInjected/HediffDef/Hediffs_BodyParts_Bionic_Empire.xml
Royalty/DefInjected/HediffDef/Hediffs_BodyParts_Prosthetic_Empire.xml
Royalty/DefInjected/ThingDef/Hediffs_BodyParts_Bionic_Empire.xml
Royalty/DefInjected/ThingDef/Hediffs_BodyParts_Prosthetic_Empire.xml

Тексты описаний почти полностью скопированы из соответствующих разделов ThingDef. Кое-где подправлены оригинальные описания.
Close #1615

#1615 Update body part descriptions. Revisit original descriptions

---

Anomaly/DefInjected/PawnKindDef/Forms.xml

Фиксы в описаниях прибывающих

---

Anomaly/DefInjected/ThingDef/Items_Various.xml
Biotech/DefInjected/ThingDef/Plants_Special.xml
Core/DefInjected/BackstoryDef/Offworld_Glitterworld_Adult.xml
Core/DefInjected/BackstoryDef/Offworld_Medieval_Adult.xml
Core/DefInjected/RecipeDef/ImpliedDefs.xml
Core/Keyed/Misc_Gameplay.xml
Ideology/DefInjected/MemeDef/Memes_Misc.xml
Odyssey/DefInjected/RulePackDef/RulePacks_Art_Statues.xml
Odyssey/DefInjected/RulePackDef/RulePacks_Maps.xml
Odyssey/DefInjected/ThingDef/Buildings_Misc.xml

- Применил где надо длинное тире с неразрывным пробелом
- Исправил кодировку в паре файлов (не используемых игрой)
- Удалил оставшиеся точки из .reportString
- Удалил точки из пары тултипов
- Добавил явное "заварить психиновый чай x4" вместо дефолтного "изготовить психиновый чай x4"

Minor and autotest fixes
